services:
  - type: web
    name: uretekure
    env: ruby
    buildCommand: |
      bundle install
      yarn install
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: a205e44087e6078c6973e31b6f974a07
    autoDeploy: true
    plan: free
    region: oregon
    buildFilter:
      paths:
        - ./
    migrations:
      run: bundle exec rails db:migrate && bundle exec rails db:seed
